"""Create mahasiswa table

Revision ID: 320c928be38c
Revises:
Create Date: 2026-04-12 14:12:08.966986

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "320c928be38c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mahasiswa",
        sa.Column("NIM", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column("nama", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sex", sa.Enum("L", "P", name="sexsenum"), nullable=False),
        sa.Column(
            "agama",
            sa.Enum(
                "islam",
                "kristen",
                "katolik",
                "buddha",
                "hindu",
                "konghucu",
                name="religionsenum",
            ),
            nullable=False,
        ),
        sa.Column("angkatan", mysql.YEAR(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("NIM"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mahasiswa")
    # ### end Alembic commands ###
