"""Create keketatan table

Revision ID: 6999e5a6a382
Revises: df00950adc5e
Create Date: 2026-04-18 12:11:28.738245

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6999e5a6a382"
down_revision: Union[str, Sequence[str], None] = "df00950adc5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keketatan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("academic_year_id", sa.Integer(), nullable=True),
        sa.Column("tampung", sa.Integer(), nullable=False),
        sa.Column("realisasi", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["academic_year_id"],
            ["academic_year.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("keketatan")
    # ### end Alembic commands ###
