"""Change angkatan column into academic_year_id from mahasiswa table

Revision ID: bafdc97b4a34
Revises: d16de6789bd0
Create Date: 2026-04-15 12:09:54.228529

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "bafdc97b4a34"
down_revision: Union[str, Sequence[str], None] = "d16de6789bd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mahasiswa", sa.Column("academic_year_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        op.f("fk_mahasiswa_angkatan_academic_year"), "mahasiswa", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_mahasiswa_academic_year_id_academic_year",
        "mahasiswa",
        "academic_year",
        ["academic_year_id"],
        ["id"],
    )
    op.drop_column("mahasiswa", "angkatan")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mahasiswa",
        sa.Column("angkatan", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(
        "fk_mahasiswa_academic_year_id_academic_year", "mahasiswa", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_mahasiswa_angkatan_academic_year"),
        "mahasiswa",
        "academic_year",
        ["angkatan"],
        ["id"],
    )
    op.drop_column("mahasiswa", "academic_year_id")
    # ### end Alembic commands ###
