"""Create academic_year and modify mahasiswa

Revision ID: d16de6789bd0
Revises: 320c928be38c
Create Date: 2026-04-14 22:18:29.172654

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d16de6789bd0"
down_revision: Union[str, Sequence[str], None] = "320c928be38c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "academic_year",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_academic_year_year"), "academic_year", ["year"], unique=True
    )
    op.alter_column(
        "mahasiswa",
        "angkatan",
        existing_type=mysql.YEAR(),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.alter_column(
        "mahasiswa", "created_at", existing_type=mysql.DATETIME(), nullable=False
    )
    op.alter_column(
        "mahasiswa", "updated_at", existing_type=mysql.DATETIME(), nullable=False
    )
    op.create_foreign_key(
        "fk_mahasiswa_angkatan_academic_year",
        "mahasiswa",
        "academic_year",
        ["angkatan"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_mahasiswa_angkatan_academic_year", "mahasiswa", type_="foreignkey"
    )
    op.alter_column(
        "mahasiswa", "updated_at", existing_type=mysql.DATETIME(), nullable=True
    )
    op.alter_column(
        "mahasiswa", "created_at", existing_type=mysql.DATETIME(), nullable=True
    )
    op.alter_column(
        "mahasiswa",
        "angkatan",
        existing_type=sa.Integer(),
        type_=mysql.YEAR(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_academic_year_year"), table_name="academic_year")
    op.drop_table("academic_year")
    # ### end Alembic commands ###
