"""Create peminatan table

Revision ID: df00950adc5e
Revises: bafdc97b4a34
Create Date: 2026-04-17 12:31:32.870607

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df00950adc5e"
down_revision: Union[str, Sequence[str], None] = "bafdc97b4a34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "peminatan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "jalur",
            sa.Enum("snbp", "snbt", "mandiri", name="jalurenum"),
            nullable=False,
        ),
        sa.Column("peminat", sa.Integer(), nullable=False),
        sa.Column("baru", sa.Integer(), nullable=False),
        sa.Column("lulus", sa.Integer(), nullable=False),
        sa.Column("academic_year_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["academic_year_id"],
            ["academic_year.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("peminatan")
    # ### end Alembic commands ###
