"""create mahasiswa table

Revision ID: 7b0ed9fa0816
Revises:
Create Date: 2026-04-11 23:40:46.547851

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b0ed9fa0816"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mahasiswa",
        sa.Column("nama", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("NIM", sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
        sa.Column("sex", sa.Enum("L", "P", name="sexsenum"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("NIM"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mahasiswa")
    # ### end Alembic commands ###
